package org.example.enums;

public enum ConfigJson {
  ANDROID_APP_ACTIVITY, ANDROID_APP_PACKAGE, ANDROID_DEVICE_NAME,
  ANDROID_UDID, ANDROID_SYSTEM_PORT, ANDROID_CHROMEDRIVER_PORT, ANDROID_EMULATOR,
  APPIUM_URL, AVD_LAUNCH_TIMEOUT,
  IOS_DEVICE_NAME, IOS_UDID, IOS_WDA_LOCAL_PORT, IOS_WEBKIT_DEBUG_PROXY_PORT,
  IOS_BUNDLE_ID,
  PLATFORM
}
